export type ButtonVariant = "default" | "destructive" | "outline" | "secondary" | "ghost" | "link";

export type ButtonSize = "default" | "sm" | "lg" | "icon";

export type IconName =
  | "chevronUp"
  | "chevronDown"
  | "chevronRight"
  | "chevronLeft"
  | "arrowRight"
  | "arrowLeft"
  | "arrowUpRight"
  | "arrowRightLong"
  | "arrowLeftLong"
  | "close"
  | "menu"
  | "search"
  | "searchX"
  | "globe"
  | "quote"
  // Status & Feedback
  | "check"
  | "refresh"
  | "info"
  | "warning"
  | "error"
  | "success"
  | "helpCircle"
  | "loader"
  // Sosial Media & Kontak
  | "email"
  | "instagram"
  | "facebook"
  | "twitter"
  | "discord"
  | "github"
  | "linkedin"
  // Navigasi Aplikasi
  | "home"
  | "about"
  | "projects"
  | "folder"
  | "blog"
  | "gallery"
  | "settings"
  | "notifications"
  | "logOut"
  // Aksi
  | "edit"
  | "trash"
  | "eye"
  | "eyeOff"
  | "copy"
  | "clipboard"
  | "share"
  | "plus"
  | "minus"
  // Tech Stack
  | "react"
  | "nextjs"
  | "typescript"
  | "nodejs"
  | "tailwind"
  | "flutter"
  | "reactNative"
  | "figma"
  | "adobeXd"
  | "vue"
  | "angular"
  | "graphql"
  | "vercel"
  | "docker"
  | "git"
  | "python"
  | "javascript"
  | "aws"
  | "firebase"
  | "golang"
  | "laravel"
  | "mongodb"
  | "mysql"
  | "stripe"
  | "supabase"
  | "svelte"
  | "threejs"
  | "astro"
  | "kotlin"
  | "swift"
  | "rust"
  | "prisma"
  | "server"
  | "vscode"
  // File Types
  | "html"
  | "css"
  | "json"
  | "markdown"
  | "document"
  | "fileCode"
  | "folderOpen"
  | "settingsGear"
  | "searchFile"
  // Lainnya
  | "gitBranch"
  | "radioTower";
